# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

r:
  - oldrel
  - release
  - devel

cache: packages

r_packages:
  - devtools

r_binary_packages:


before_install:
  - cd sample

after_success:
  - Rscript -e 'covr::codecov()'
